services:
  - type: web
    name: securascan-back
    env: docker
    dockerfilePath: ./secureScan_Back/Dockerfile.backend
    dockerContext: ./secureScan_Back
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: RUST_LOG
        value: info
      # FRONT_ORIGIN will be set after frontend URL is known

  - type: static_site
    name: securascan-front
    buildCommand: cd secureScan_Front && npm ci && npm run build
    staticPublishPath: secureScan_Front/dist
    autoDeploy: true
    # VITE_API_URL will be set to backend URL (set via Render UI or CI before deploy)
