services:
  - type: web
    name: securascan-back
    env: docker
    plan: free
    dockerfilePath: ./secureScan_Back/Dockerfile.backend
    dockerContext: ./secureScan_Back
    autoDeploy: true
    envVars:
      - key: RUST_LOG
        value: info
      # Do NOT set BIND_ADDR here; the startup script reads $PORT at runtime and
      # sets BIND_ADDR accordingly so the service uses the platform-provided port.

  - type: static
    name: securascan-front
    env: static
    plan: free
    root: secureScan_Front
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    autoDeploy: true
