version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: securascan-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: securascan
      POSTGRES_USER: securascan
      # DO NOT store real passwords here. For production, inject secrets via
      # environment secrets or a secrets manager. Replace the placeholder below
      # with a secure value in your local dev environment only.
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-__REPLACE_WITH_SECURE_PASSWORD__}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securascan -d securascan"]
      interval: 5s
      timeout: 3s
      retries: 10


  pgadmin:
    image: dpage/pgadmin4:8
    container_name: securascan-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      # PGAdmin password must be set via environment in development. In
      # production use GitHub Actions secrets / Docker secrets or a Vault.
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-__REPLACE_WITH_SECURE_PASSWORD__}"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
