version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: securascan-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: securascan
      POSTGRES_USER: securascan
      POSTGRES_PASSWORD: change-me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securascan -d securascan"]
      interval: 5s
      timeout: 3s
      retries: 10


  pgadmin:
    image: dpage/pgadmin4:8
    container_name: securascan-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
